{
     "button":[
     {
           "name":"额度自测",
           "sub_button":[
            {    
               "type":"view",
               "name":"额度自测",
               "url":"http://weixin.yuanbaopu.com/amountSelfTest/amountSelfTestPage.do?from=singlemessage&isappinstalled=0"
            },
            {
               "type":"view",
               "name":"计息还款",
               "url":"http://finance.sina.com.cn/calc/house_early_repayment.html"
            },
            {    
                "type":"view",
               "name":"贷款进度",
               "url":"http://app.yuanbaopu.com/?loanlist=show"
            }]
      },{
           "name":"电商贷",
           "sub_button":[
            {    
               "type":"view",
               "name":"电商贷介绍",
               "url":"http://mp.weixin.qq.com/s?__biz=MzA5NTU2NTMxMw==&mid=400545322&idx=1&sn=f51bdab4c2e4c334e188dcf63129d3b7&scene=18#wechat_redirect"
            },
            {
               "type":"view",
               "name":"常见问题",
               "url":"http://m.zz91.com/yuanbaopu/help.html"
            },
            {    
                "type":"view",
               "name":"申请贷款",
               "url":"https://www.yuanbaopu.com/promotionflow/index.htm?fm=mf_wx_ld&mk=double10"
            },
            {    
                "type":"view",
               "name":"下载APP",
               "url":"http://a.app.qq.com/o/simple.jsp?pkgname=com.yuanbaopu.app"
            }]
      },
      {
           "type":"click",
           "name":"问卷调查",
           "key":"dc"
       }]
 }